In [4]:
import numpy as np
branches = {
    "Branch_A": [1450, 1300, 1580, 1620, 1705, 1800],
    "Branch_B": [1200, 1100, 1250, 1400, 1500, 1600],
    "Branch_C": [2000, 1950, 2100, 2050, 2200, 2150],
    "Branch_D": [980, 1050, 1150, 1200, 1300, 1280]
}

data_matrix = np.array(list(branches.values()))
print("Transaction Matrix:\n", data_matrix)

totals = []
for row in data_matrix:
    totals.append(np.sum(row))

print("\nTotals Per Branch:", totals)

max_index = totals.index(max(totals))
branch_names = list(branches.keys())
print("\nHighest Performing Branch:", branch_names[max_index])

avg_volume = data_matrix.flatten().mean()
print("\nAverage Monthly Volume:", avg_volume)

reshaped_matrix = data_matrix.reshape(3, 8)
print("\nReshaped (3x8):\n", reshaped_matrix)

print("""
Explanation:
Reshaping changes how the data is arranged in the array without changing the values.
When we reshape from 4×6 to 3×8, the original meaning of rows as branches and
columns as months is lost. The numbers are still there, but they no longer represent
specific branches or months, so the reshaped array cannot be used for analysis.
""")


Transaction Matrix:
 [[1450 1300 1580 1620 1705 1800]
 [1200 1100 1250 1400 1500 1600]
 [2000 1950 2100 2050 2200 2150]
 [ 980 1050 1150 1200 1300 1280]]

Totals Per Branch: [np.int64(9455), np.int64(8050), np.int64(12450), np.int64(6960)]

Highest Performing Branch: Branch_C

Average Monthly Volume: 1538.125

Reshaped (3x8):
 [[1450 1300 1580 1620 1705 1800 1200 1100]
 [1250 1400 1500 1600 2000 1950 2100 2050]
 [2200 2150  980 1050 1150 1200 1300 1280]]

Explanation:
Reshaping changes how the data is arranged in the array without changing the values.
When we reshape from 4×6 to 3×8, the original meaning of rows as branches and
columns as months is lost. The numbers are still there, but they no longer represent
specific branches or months, so the reshaped array cannot be used for analysis.

