In [ ]:
import numpy as np

transactions = np.array([
    [1200, 1350, 1600, 1450, 1700, 1550],  # Branch 1
    [1100, 1250, 1400, 1300, 1500, 1600],  # Branch 2
    [1800, 1750, 1900, 2000, 2100, 2050],  # Branch 3
    [1000, 1150, 1200, 1400, 1300, 1250]   # Branch 4
])

print("Transaction Array:\n", transactions)
totals = np.sum(transactions, axis=1)
print("\nTotal Transactions per Branch:", totals)

highest_branch = np.argmax(totals) + 1
print("\nBranch with Highest Total Transactions:", highest_branch)

average_monthly = np.mean(transactions)
print("\nAverage Monthly Transaction Volume:", average_monthly)

reshaped = transactions.reshape(3, 8)
print("\nReshaped Array (3x8):\n", reshaped)


Transaction Array:
 [[1200 1350 1600 1450 1700 1550]
 [1100 1250 1400 1300 1500 1600]
 [1800 1750 1900 2000 2100 2050]
 [1000 1150 1200 1400 1300 1250]]

Total Transactions per Branch: [ 8850  8150 11600  7300]

Branch with Highest Total Transactions: 2

Average Monthly Transaction Volume: 1495.8333333333333

Reshaped Array (3x8):
 [[1200 1350 1600 1450 1700 1550 1100 1250]
 [1400 1300 1500 1600 1800 1750 1900 2000]
 [2100 2050 1000 1150 1200 1400 1300 1250]]
